site_name: System Design Journey
site_description: Daily exploration of FAANG-level system design concepts
site_author: Sushil Mayengbam
site_url: https://hawaijar.github.io/System-Design-Journey

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Daily Logs:
    - Overview: daily/index.md
    - Day 1 (Oct 24): daily/2024-10-24.md
    - Day 2 (Oct 25): daily/2024-10-25.md
  - Topics:
    - Overview: topics/index.md
    - Building Blocks: topics/building-blocks.md
    - Interview Approach: topics/interview-approach.md
    - Scalability Patterns: topics/scalability-patterns.md
  - Resources: resources.md
  - About: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hawaijar
